UserApplication/Controllers/SuperAdminController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserApplication.Models;
using static UserApplication.Models.UserViewModel;

namespace UserApplication.Controllers
{
    public class SuperAdminController : Controller
    {
        private UserDbContext obj = new UserDbContext();
        // GET: SuperAdmin
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// Display list of all users
        /// </summary>
        /// <returns></returns>
        public ActionResult UserList()
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            var listOfUsers = obj.Users.Where(u => u.RoleId != 1).ToList();
           return View(listOfUsers);
        }
        /// <summary>
        /// GET:Super Admin can create user
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult CreateUser()
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            //Dropdown for Role List
            List<Role> List = obj.Roles.Where(u => u.RoleId != 1 ).ToList();
            ViewBag.RoleList = new SelectList(List, "RoleId", "RoleName");

            //Dropdown for the Course List
            List<Course> Lists = obj.Courses.ToList();
            ViewBag.CourseLists = new SelectList(Lists, "CourseId", "CourseName");

            //Dropdown for the Country List
            List<Country> List1 = obj.Countries.ToList();
            ViewBag.CountryList1 = new SelectList(List1, "CountryId", "CountryName");

            return View();
        }
        /// <summary>
        /// POST:Super Admin can create user
        /// </summary>
        /// <param name="userViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateUser(UserViewModel userViewModel)
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            //Dropdown for Role List
            List<Role> List = obj.Roles.Where(u => u.RoleId != 1).ToList();
            ViewBag.RoleList = new SelectList(List, "RoleId", "RoleName");

            //Dropdown for Course List
            List<Course> Lists = obj.Courses.ToList();
            ViewBag.CourseLists = new SelectList(Lists, "CourseId", "CourseName");

            //Dropdown for Country List
            List<Country> List1 = obj.Countries.ToList();
            ViewBag.CountryList1 = new SelectList(List1, "CountryId", "CountryName");

            //Object of address table
            Address address = new Address();
            //Binding the fields of address table
            address.AddressId = userViewModel.AddressId;
            address.CountryId = userViewModel.CountryId;
            address.StateId = userViewModel.StateId;
            address.CityId = userViewModel.CityId;
            address.Zipcode = userViewModel.Zipcode;

            obj.Addresses.Add(address);  //Insert data in address table
            obj.SaveChanges();           //Save data in database
            int latestAddressId = address.AddressId;

            //Object of user table 
            User user = new User();
            //Binding the fields 
            user.UserId = userViewModel.UserId;
            user.FirstName = userViewModel.FirstName;
            user.LastName = userViewModel.LastName;
            user.Gender = userViewModel.Gender;
            user.Hobbies = userViewModel.Hobbies;
            user.Password = userViewModel.Password;
            user.Email = userViewModel.Email;
            user.DOB = userViewModel.DOB;
            user.DateCreated = DateTime.Now;
            user.DateModified = DateTime.Now;
            user.IsActive = userViewModel.IsActive;
            user.RoleId = userViewModel.RoleId;
            user.CourseId = userViewModel.CourseId;
            user.AddressLine1 = userViewModel.AddressLine1;
            user.AddressLine2 = userViewModel.AddressLine2;
            user.AddressId = latestAddressId;

            obj.Users.Add(user);      //Insert data in user table
            obj.SaveChanges();         //Save data in database

            int latestUserId = user.UserId;

            UserInRole userInRole = new UserInRole();
            userInRole.UserId = latestUserId;
            userInRole.RoleId = userViewModel.RoleId;

            obj.UserInRoles.Add(userInRole);
            obj.SaveChanges();

            return RedirectToAction("UserList");
        }
        /// <summary>
        /// Get all countries
        /// </summary>
        SqlConnection UserDbContext = new SqlConnection(ConfigurationManager.ConnectionStrings["UserDbContext"].ConnectionString);
        public DataSet Get_Country()
        {
            SqlCommand com = new SqlCommand("Select * from Countries", UserDbContext);
            SqlDataAdapter da = new SqlDataAdapter(com);
            DataSet ds = new DataSet();
            da.Fill(ds);
            return ds;
        }

        /// <summary>
        /// Get all states
        /// </summary>
        /// <param name="CountryId"></param>
        /// <returns></returns>
        public DataSet Get_State(string CountryId)
        {
            SqlCommand com = new SqlCommand("Select * from States where CountryId=@countryid", UserDbContext);
            com.Parameters.AddWithValue("@countryid", CountryId);
            SqlDataAdapter da = new SqlDataAdapter(com);
            DataSet ds = new DataSet();
            da.Fill(ds);
            return ds;
        }

        /// <summary>
        /// Get all cities
        /// </summary>
        /// <param name="StateId"></param>
        /// <returns></returns>
        public DataSet Get_City(string StateId)
        {
            SqlCommand com = new SqlCommand("Select * from Cities where StateId=@stateid", UserDbContext);
            com.Parameters.AddWithValue("@stateid", StateId);
            SqlDataAdapter da = new SqlDataAdapter(com);
            DataSet ds = new DataSet();
            da.Fill(ds);
            return ds;
        }
        /// <summary>
        /// Binding the country
        /// </summary>
        public void Country_Bind()
        {
            DataSet ds = Get_Country();
            List<SelectListItem> countrylist = new List<SelectListItem>();

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                countrylist.Add(new SelectListItem { Text = dr["CountryName"].ToString(), Value = dr["CountryId"].ToString() });

            }
            ViewBag.Country = countrylist;
        }
        /// <summary>
        /// Binding the state
        /// </summary>
        /// <param name="CountryId"></param>
        /// <returns></returns>
        public JsonResult State_Bind(string CountryId)
        {
            DataSet ds = Get_State(CountryId);
            List<SelectListItem> statelist = new List<SelectListItem>();

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                statelist.Add(new SelectListItem { Text = dr["StateName"].ToString(), Value = dr["StateId"].ToString() });
            }
            return Json(statelist, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// Binding the city
        /// </summary>
        /// <param name="StateId"></param>
        /// <returns></returns>
        public JsonResult City_Bind(string StateId)
        {
            DataSet ds = Get_City(StateId);
            List<SelectListItem> citylist = new List<SelectListItem>();

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                citylist.Add(new SelectListItem { Text = dr["CityName"].ToString(), Value = dr["CityId"].ToString() });
            }
            return Json(citylist, JsonRequestBehavior.AllowGet);
        }
        /// <summary>
        /// GET:Super Admin can edit the user details
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult EditUser(int id)
        {
            if (Session["Login"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            //Dropdown for Role List
            List<Role> List = obj.Roles.Where(u => u.RoleId != 1).ToList();
            ViewBag.RoleList = new SelectList(List, "RoleId", "RoleName");

            //Dropdown for Course List
            List<Course> Lists = obj.Courses.ToList();
            ViewBag.CourseLists = new SelectList(Lists, "CourseId", "CourseName");

            List<Country> CountryList = obj.Countries.ToList();
            ViewBag.CountryLists = new SelectList(CountryList, "CountryId", "CountryName");

            List<State> StateList = obj.States.ToList();
            ViewBag.StateLists = new SelectList(StateList, "StateId", "StateName");

            List<City> CityList = obj.Cities.ToList();
            ViewBag.CityLists = new SelectList(CityList, "CityId", "CityName");

            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Object of user table
            User objUser = obj.Users.Find(id);
            //Object of user view model table
            UserViewModel objUserViewModel = new UserViewModel();

            objUserViewModel.UserId = objUser.UserId;
            objUserViewModel.FirstName = objUser.FirstName;
            objUserViewModel.LastName = objUser.LastName;
            objUserViewModel.Gender = objUser.Gender;
            objUserViewModel.Hobbies = objUser.Hobbies;
            objUserViewModel.Email = objUser.Email;
            objUserViewModel.Password = objUser.Password;

UserApplication/Views/SuperAdmin/AssignSubjectForCourse.cshtml
@model UserApplication.Models.SubjectInCourse
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Applicaion Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            @Html.ActionLink("User List", "UserList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Course", "CreateCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course List", "CourseList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Subject List", "SubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Teacher", "AssignSubjectToTeacher", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Subject", "CreateSubject", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Course", "AssignSubjectForCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Teacher Subject List", "TeacherSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course And Subject List", "CourseAndSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-right">
                @Html.ActionLink("LogOut", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })
            </ul>
        </div>
    </div>
</div>
@{
    ViewBag.Title = "AssignSubjectForCourse";
    Layout = "~/Views/Shared/_LogOutPage.cshtml";
}
<h1 align="middle"><b>VIDHYA NIKETAN</b></h1>
<h2 align="middle"><i>THE INFINITE CAMPUS</i></h2>
<center><img src=" http://www.vidyaniketansaket.in/image/f-logo.png" width=" 90" height=" 90" /></center>

<h2>Assign Subject To Course</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4> </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseId, "CourseId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CourseId", ViewBag.CourseList as SelectList, "--select--", htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", ViewBag.SubjectList as SelectList, "--select--", htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>

    @Html.Partial("_BackToListButtonPartial")
    @Html.Partial("_CreateCourseButtonPartial")
    @Html.Partial("_AddSubjectButtonPartial")
</div>

UserApplication/Views/SuperAdmin/AssignSubjectToTeacher.cshtml
@model UserApplication.Models.TeacherInSubject
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Applicaion Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            @Html.ActionLink("User List", "UserList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Course", "CreateCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course List", "CourseList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Subject List", "SubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Teacher", "AssignSubjectToTeacher", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Subject", "CreateSubject", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Course", "AssignSubjectForCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Teacher Subject List", "TeacherSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course And Subject List", "CourseAndSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-right">
                @Html.ActionLink("LogOut", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })
            </ul>
        </div>
    </div>
</div>
@{
    ViewBag.Title = "AssignSubjectToTeacher";
    Layout = "~/Views/Shared/_LogOutPage.cshtml";
}
<h1 align="middle"><b>VIDHYA NIKETAN</b></h1>
<h2 align="middle"><i>THE INFINITE CAMPUS</i></h2>
<center><img src=" http://www.vidyaniketansaket.in/image/f-logo.png" width=" 90" height=" 90" /></center>

<h2>Assign Subject To Teacher</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4> </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", ViewBag.TeacherList as SelectList, "--select--", htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", ViewBag.SubjectList as SelectList, "--select--", htmlAttributes: new { @class = "form-control", required = "required" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.Partial("_BackToListButtonPartial")
</div>

UserApplication/Views/SuperAdmin/CourseAndSubjectList.cshtml
@model IEnumerable<UserApplication.Models.SubjectInCourse>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Applicaion Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            @Html.ActionLink("User List", "UserList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Course", "CreateCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course List", "CourseList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Subject List", "SubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Teacher", "AssignSubjectToTeacher", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Subject", "CreateSubject", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Course", "AssignSubjectForCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Teacher Subject List", "TeacherSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course And Subject List", "CourseAndSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-right">
                @Html.ActionLink("LogOut", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })
            </ul>
        </div>
    </div>
</div>
@{
    ViewBag.Title = "CourseAndSubjectList";
    Layout = "~/Views/Shared/_LogOutPage.cshtml";
}
<h1 align="middle"><b>VIDHYA NIKETAN</b></h1>
<h2 align="middle"><i>THE INFINITE CAMPUS</i></h2>
<center><img src=" http://www.vidyaniketansaket.in/image/f-logo.png" width=" 90" height=" 90" /></center>

<h2>Course And Subject List</h2>

<p>
    @Html.ActionLink(" ", " ")
</p>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Course.CourseName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Course.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject.SubjectName)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.SubjectInCourseId }) |
                    @Html.ActionLink("Details", "Details", new { id=item.SubjectInCourseId }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.SubjectInCourseId })*@
                @Html.ActionLink("Delete", "DeleteCourseAndSubject", new { id= item.SubjectInCourseId})
            </td>
        </tr>
    }

</table>
<p> @Html.Partial("_BackToListButtonPartial")</p>

UserApplication/Views/SuperAdmin/CourseList.cshtml
@model IEnumerable<UserApplication.Models.Course>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Applicaion Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            @Html.ActionLink("User List", "UserList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Course", "CreateCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course List", "CourseList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Subject List", "SubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Teacher", "AssignSubjectToTeacher", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Subject", "CreateSubject", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Course", "AssignSubjectForCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Teacher Subject List", "TeacherSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course And Subject List", "CourseAndSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-right">
                @Html.ActionLink("LogOut", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })
            </ul>
        </div>
    </div>
</div>
@{
    ViewBag.Title = "CourseList";
    Layout = "~/Views/Shared/_LogOutPage.cshtml";

}
<h1 align="middle"><b>VIDHYA NIKETAN</b></h1>
<h2 align="middle"><i>THE INFINITE CAMPUS</i></h2>
<center><img src=" http://www.vidyaniketansaket.in/image/f-logo.png" width=" 90" height=" 90" /></center>

<h2>Course List</h2>

<p>
    @Html.ActionLink(" ", " ")
</p>
<table class="table table-bordered table-responsive table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CourseName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id=item.CourseId }) |
                    @Html.ActionLink("Details", "Details", new { id=item.CourseId }) |*@
                @Html.ActionLink("Delete Course", "DeleteCourse", new { id = item.CourseId })
            </td>
        </tr>

    }


</table>
<p>
    @Html.Partial("_AddSubjectButtonPartial")
    @Html.Partial("_BackToListButtonPartial")
    @Html.Partial("_CreateCourseButtonPartial")
</p>

UserApplication/Views/SuperAdmin/CreateCourse.cshtml
@model UserApplication.Models.Course
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Applicaion Name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        </div>
        <div class="navbar-collapse collapse">
            @Html.ActionLink("User List", "UserList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Course", "CreateCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course List", "CourseList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Subject List", "SubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Teacher", "AssignSubjectToTeacher", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Add Subject", "CreateSubject", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Assign Subject To Course", "AssignSubjectForCourse", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Teacher Subject List", "TeacherSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            @Html.ActionLink("Course And Subject List", "CourseAndSubjectList", "SuperAdmin", new { area = "" }, new { @class = "navbar-brand" })
            <ul class="nav navbar-right">
                @Html.ActionLink("LogOut", "LogOut", "User", new { area = "" }, new { @class = "navbar-brand" })
            </ul>
        </div>
    </div>
</div>
@{
    ViewBag.Title = "CreateCourse";
    Layout = "~/Views/Shared/_LogOutPage.cshtml";
}
<h1 align="middle"><b>VIDHYA NIKETAN</b></h1>
<h2 align="middle"><i>THE INFINITE CAMPUS</i></h2>
<center><img src=" http://www.vidyaniketansaket.in/image/f-logo.png" width=" 90" height=" 90" /></center>

<h2>Add New Course</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4> </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CourseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CourseName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.CourseName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.Partial("_AddSubjectButtonPartial")
    @Html.Partial("_BackToListButtonPartial")

</div>